import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased font-sans`}
      >
        <div className="bg-st-ocean text-white font-semibold p-4 flex justify-between">
          <h1 className="text-xl"><Link href="/">Symptom Tracker</Link></h1>
          <nav>
            <ul className="flex gap-4 text-sm">
              <li><Link href="/daily">Daily</Link></li>
              <li><Link href="#">Overview</Link></li>
              <li><Link href="#">Settings</Link></li>
              <li><Link href="#">Login/Signup</Link></li>
            </ul>
          </nav>
        </div>
        <div className="px-5 py-7">
          {children}
        </div>
      </body>
    </html>
  );
}
